import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "notes/projects/flatground-tricks-source.json");
const jsPath = path.join(root, "notes/projects/flatground-tricks-data.js");
const csvPath = path.join(root, "notes/projects/flatground-tricks-data.csv");
const htmlPath = path.join(root, "notes/projects/flatground-tricks.html");

const args = process.argv.slice(2);
const appendIndex = args.indexOf("--append");
const checkOnly = args.includes("--check");
if (appendIndex >= 0 && checkOnly) throw new Error("--append and --check cannot be combined");

let data = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
if (!Array.isArray(data)) throw new Error("Source data must be an array");

if (appendIndex >= 0) {
  const batchArg = args[appendIndex + 1];
  if (!batchArg) throw new Error("Usage: node scripts/flatground-sync.mjs --append path/to/part-9.json");
  const batchPath = path.resolve(process.cwd(), batchArg);
  const batch = JSON.parse(fs.readFileSync(batchPath, "utf8"));
  if (!Array.isArray(batch) || batch.length !== 100) throw new Error("Append batch must contain exactly 100 tricks");
  const expectedStart = data.length + 1;
  const expectedPart = Math.floor(data.length / 100) + 1;
  if (batch[0]?.num !== expectedStart) throw new Error(`Batch must begin at trick #${expectedStart}`);
  for (let i = 0; i < batch.length; i++) {
    const d = batch[i];
    const expectedNum = expectedStart + i;
    if (d.num !== expectedNum) throw new Error(`Append batch numbering error: expected #${expectedNum}, found #${d.num}`);
    if (d.part !== expectedPart) throw new Error(`Append batch must use Part ${expectedPart}; trick #${d.num} says Part ${d.part}`);
    if (!Number.isFinite(d.seconds) || d.seconds < 0) throw new Error(`Invalid timestamp at #${d.num}`);
    if (i && d.seconds <= batch[i-1].seconds) throw new Error(`Append timestamps must increase strictly; check #${d.num}`);
  }
  data = [...data, ...batch];
}

const formatTimestamp = seconds => {
  const minutes = Math.floor(seconds / 60);
  const remainder = (seconds - minutes * 60).toFixed(1).padStart(4, "0");
  return `${minutes}:${remainder}`;
};
const csvEscape = value => {
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const generatedJs =
  "/* Generated from flatground-tricks-source.json. Do not edit this file directly. */\n" +
  "window.FLATGROUND_TRICKS_DATA=[\n" +
  data.map((d,i) => JSON.stringify(d) + (i < data.length - 1 ? "," : "")).join("\n") +
  "\n];\n";

const generatedCsv = [
  ["trick_number","trick_name","stance","part","caption_timestamp"],
  ...data.map(d => [d.num,d.name,d.stance,d.part,formatTimestamp(d.seconds)])
].map(row => row.map(csvEscape).join(",")).join("\n") + "\n";

const count = data.length;
let html = fs.readFileSync(htmlPath, "utf8");
html = html
  .replace(/A sortable digital compendium of \d+ flatground tricks/g, `A sortable digital compendium of ${count} flatground tricks`)
  .replace(/aria-label="\d+-trick stance overview"/g, `aria-label="${count}-trick stance overview"`)
  .replace(/>\d+ \/ \d+<\/span>/g, `>${count} / ${count}</span>`);

const outputs = [
  [sourcePath, JSON.stringify(data,null,2) + "\n"],
  [jsPath, generatedJs],
  [csvPath, generatedCsv],
  [htmlPath, html]
];

if (checkOnly) {
  const mismatches = outputs
    .filter(([file, expected]) => fs.readFileSync(file, "utf8") !== expected)
    .map(([file]) => path.relative(root, file));
  if (mismatches.length) {
    throw new Error("Generated files are out of sync: " + mismatches.join(", ") + ". Run node scripts/flatground-sync.mjs");
  }
  execFileSync(process.execPath, [path.join(root, "scripts/validate-flatground-tricks.mjs")], { stdio: "inherit" });
  console.log(`Flatground sync check passed: ${count} tricks.`);
  process.exit(0);
}

const originals = new Map(outputs.map(([file]) => [file, fs.readFileSync(file, "utf8")]));
try {
  for (const [file, content] of outputs) fs.writeFileSync(file, content);
  execFileSync(process.execPath, [path.join(root, "scripts/validate-flatground-tricks.mjs")], { stdio: "inherit" });
} catch (error) {
  for (const [file, content] of originals) fs.writeFileSync(file, content);
  throw error;
}
console.log(`Flatground files synchronized: ${count} tricks across ${Math.ceil(count/100)} parts.`);
